### ISSUE TITLE
Update javascript code on readme/doc page

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#10]
At page http://tildehash.com/?page=hashover the javascript example is incorrect and does not work with the latest version. 

Currently:

	<script type="text/javascript">
		var rows="4";        // Sets "Comments" field height
		var name_on="no";    // Disables "Name" field
		var passwd_on="no";  // Disables "Password" field
		var email_on="no";   // Disables "E-mail" field
		var sites_on="no";   // Disables "Website" field
	</script> 

This should be stated instead: 

	<script type="text/javascript">
		var rows="4";        // Sets "Comments" field height
		var nickname_on = false;    // Disables "Name" field
		var email_on = false;   // Disables "E-mail" field
		var website_on = false;   // Disables "Website" field
		var password_on = false;  // Disables "Password" field
	</script>

**Comment by jacobwb** [comment]
The latest version is 1.0, that version is what the documentation is for, and it is valid for that version.

2.0 isn't finished yet, it isn't stable. And it isn't documented, because many things will change.
