### ISSUE TITLE
Issues when putting hashover into a subfolder and not root

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#14]
In my POV scripts should run in subfolders, at least be able to.

It seems that hashover is not yet ready for this. I wanted to put all hashover files into a folder `comments` to have the script separate from all other scripts running on my server.

When doing so, I get:

```
HashOver - Error: Failed to create comment thread directory at "./comments/hashover/pages/example-page" 
```

I have set the necessary file permissions, so the bug should be somewhere else.

**Comment by q2apro** [comment]
Just one more note: It is quite important to have the script running in a separate folder, so that the user can assign a quota to it. This way the quota prevents hackers, that infiltrate the server using hashover, to change system files or access the other server resources/folders. 

I would mark this enhancement as highly important because it is about security.

**Comment by jacobwb** [comment]
I thought having HashOver run from a sub-directory was possible, but perhaps I changed something along the way that broke it.

**Comment by q2apro** [comment]
I hope this can be fixed due to security reasons.
