### ISSUE TITLE
Adding 'email_tooltip' to locales.php

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#16]
To make it clear for the user why he can enter the URL I suggest to provide an extra tooltip translation. Currently there is only: 

	'email'		=> 'E-mail Address',

which is used for the placeholder and the tooltip of the email input field.

I suggest adding: 

	'email_tooltip'	=> 'E-mail Address for notifications',

And changing in javascript-mode.php (two occurences): 

	title="' . $this->text['email'] . '"

to 

	title="' . $this->text['email_tooltip'] . '"

Maybe this could be done for all tooltips, providing separate `_tooltip` entries.

Update: Same goes for the `placeholder`.

**Comment by jacobwb** [comment]
The "Nickname" and "Password" fields already do this. Adding more is a good idea.
