### ISSUE TITLE
Just now I discovered the other repo "hashover-next"...

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#17]
Well, as I have seen from other projects on github, developers use branches in the same repo to proceed their project. 

However, as I have just discovered now, there is a new project / repo at https://github.com/jacobwb/hashover-next

Questions: 

1. Why is their no branch in this repo but another repo created instead?
2. Why is their no information in the readme (should be on top)?
3. Should I use the new 2.0 version now and ignore this repo? What is the difference between both repos?
4. Shouldn't all my reported issues be transfered to the other repo?

**Comment by jacobwb** [comment]
> Why is their no branch in this repo but another repo created instead?

Separation.

I want the HashOver 1.0 repository to show that there really is no developmental activity happening there, as there isn't going to be any 1.x releases.

> Why is their no information in the readme (should be on top)?

???

In which repository? Both have README.md files, and the readme for "hashover-next" is longer and has a few things about what 2.0's goals are, contribution guidelines, and stuff about copyright.

> Should I use the new 2.0 version now and ignore this repo? What is the difference between both repos?

You should ignore the "hashover" repository, and new issues should be opened on "hashover-next".

"hashover" is version 1.0 and doesn't receive any new code, all pull requests are rejected, and it will be completely overwritten with 2.0 when it's done. This way the "hashover" repository's commits will only show major version changes, not thousands of minor changes. You can think about "hashover" as the stable repository, and "hashover-next" as the unstable or testing repository.

> Shouldn't all my reported issues be transfered to the other repo?

I don't think that is possible to do on GitHub, short of copying and pasting them all.

I say the issues will be closed soon anyway, and as long as new issues are opened on "hashover-next" from now on, there's absolutely no problem.

**Comment by q2apro** [comment]
Good, thanks for your reply. To sum up: 

1. All my posted issues in this repo concern the new version "hashover-next".
2. I will post all new issues in the new repo.
3. Please add the notice that version 1.0 is not developped on the very top of the readme.md so that it is clear to all newbies: https://github.com/jacobwb/hashover

Merci.
