### ISSUE TITLE
Need help with the installation on LocalHost

### ISSUE THREAD

**Issue by DeniTx** [jacobwb/hashover#21]
I added all the folder to localhost using wamp server

it is showing this 

document.write("HashOver: The variable values in /hashover/scripts/secrets.php need to be UNIQUE.");

**Comment by jacobwb** [comment]
@DeniTx

You most likely need to edit the file located at `hashover/scripts/secrets.php` and change each one of the variables there to unique values. For example, the variable `$encryption_key` should be something you might normally use as a password, like "gaodino2016".

Likewise, `$notification_email` should have an e-mail address you're comfortable having notification e-mails sent to, `$admin_nickname` should be a username something like "superuser", and `$admin_password` should again be a password like "sysadmin_rock_and_roll2016".

That should remove the message.
