### ISSUE TITLE
I need Installation help for HashOver 2.0

### ISSUE THREAD

**Issue by sanzuu** [jacobwb/hashover#22]
I have uploaded hashover-next-master.zip to my website and extracted it to root directory. 
and I have done below steps:

1. add to head 
 
           <link href="/hashover/themes/default/style.css" rel="stylesheet" type="text/css" />
             <script type="text/javascript" src="/hashover/hashover.js"></script>

             <script>var canon_url = (document.querySelector('link[rel="canonical"]') != null) ? '?canon_url=' + encodeURIComponent(document.querySelector('link[rel="canonical"]').getAttribute('href')) : ''; document.write('<script src="/hashover/hashover.js' + canon_url + '"><\/script>');</script>
    
2. edit - `settings.php` 

I am unable to see a 'comment form' to my webpage. is there any html markup ?

**Comment by jacobwb** [comment]
Addressing this on HashOver 2.0: https://github.com/jacobwb/hashover-next/issues/133
