### ISSUE TITLE
Suggestion: Save time of post in 24 hours format

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#7]
Currently time gets saved with AM or PM: 

	<date>01/02/2015 - 12:00am</date>

For internationalization, I suggest to save the time in `24:00` format.

Furthermore I suggest to save the date in Format: `2015-02-01`

PS: As a workaround I am using `$cmt_date = date('H:i', strtotime($get_cmtdate[1])) . ' heute';` for now.

**Comment by jacobwb** [comment]
The saved date should be some kind of standard, yes, probably ISO 8601.
