### ISSUE TITLE
Delete comments - option for admin

### ISSUE THREAD

**Issue by q2apro** [jacobwb/hashover#8]
I could not discover the option how the admin can delete a spam comment or an unwanted comment. 

Please advice me where I can find this. Deleting each comment by deleting the xml file (opening ftp client, going to the folder, deleting) is too much effort. 

Suggestion: Provide an admin login to list all comments and a delete button. This could also be a htaccess protected folder.

**Comment by jacobwb** [comment]
You must set the `$admin_nickname` and `$admin_password` variables in `secrets.php` to unique values, and then you just need to "login" using that nickname and that password. You should then have total power to edit and delete any comment.

**Comment by q2apro** [comment]
I used this to login, however, I see no option to delete the comment. 

![capture](https://cloud.githubusercontent.com/assets/6764548/5593668/203dde1e-9228-11e4-8d01-a30f3c9a5d6c.PNG)

I am using Javascript mode.

**Comment by jacobwb** [comment]
That's odd. You shouldn't be able to use "admin" as the admin username.

Try using only English alphanumeric characters for both the admin username and admin password, perhaps the encryption doesn't handle non-English alphabet characters.

Do you get the edit button when you comment normally?

**Comment by q2apro** [comment]
I am not using "admin", I just put the name as an example. 

I am using only English characters, some capitalized.

I get the edit button when I post myself: 

![capture](https://cloud.githubusercontent.com/assets/6764548/5594721/d0a8243e-9260-11e4-8530-1d1ca3b4e11c.PNG)

**Comment by q2apro** [comment]
Yes, that is the problem! 

Changing the username "eetv" in the settings to "Eetv" brings up the edit button!

Please change the behaviour of hashover, to let the username untouched. Thanks.
